name = "ITensorChemistry"
uuid = "cbb729c8-cb01-4982-b6b1-bc32521fc628"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
Combinatorics = "1.0.2"
ITensors = "0.3.15"
PythonCall = "0.9.12"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
