name = "ITensorChemistry"
uuid = "cbb729c8-cb01-4982-b6b1-bc32521fc628"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.0.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Fermi = "9237668d-08c8-4784-b8dd-383aa52fcf74"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Combinatorics = "1.0.2"
Fermi = "0.4"
ITensors = "0.3.15"
Suppressor = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
